import {
  ChocolateQuente,
  CoffeeAmericano,
  CoffeeArabe,
  CoffeeCapuccino,
  CoffeeComLeite,
  CoffeeCubano,
  CoffeeExpresso,
  CoffeeExpressoCremoso,
  CoffeeGelado,
  CoffeeHavaiano,
  CoffeeIrlands,
  CoffeeLatte,
  CoffeeMacchiato,
  CoffeeMochaccino,
} from './assets/coffees'
import { Coffee } from './reducers/deliveries/reducer'

export const coffeesData: Coffee[] = [
  {
    id: 1,
    tags: ['Tradicional'],
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água e grãos moídos',
    price: 9.9,
    img: CoffeeExpresso,
    amountInShoppingCart: 0,
  },
  {
    id: 2,
    tags: ['Tradicional'],
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
    img: CoffeeAmericano,
    amountInShoppingCart: 0,
  },
  {
    id: 3,
    tags: ['Tradicional'],
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
    img: CoffeeExpressoCremoso,
    amountInShoppingCart: 0,
  },
  {
    id: 4,
    tags: ['Tradicional', 'Gelado'],
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    img: CoffeeGelado,
    amountInShoppingCart: 0,
  },
  {
    id: 5,
    tags: ['Tradicional', 'com leite'],
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
    img: CoffeeComLeite,
    amountInShoppingCart: 0,
  },
  {
    id: 6,
    tags: ['Tradicional', 'com leite'],
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
    img: CoffeeLatte,
    amountInShoppingCart: 0,
  },
  {
    id: 7,
    tags: ['Tradicional', 'com leite'],
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
    img: CoffeeCapuccino,
    amountInShoppingCart: 0,
  },
  {
    id: 8,
    tags: ['Tradicional', 'com leite'],
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
    img: CoffeeMacchiato,
    amountInShoppingCart: 0,
  },
  {
    id: 9,
    tags: ['Tradicional', 'com leite'],
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    img: CoffeeMochaccino,
    amountInShoppingCart: 0,
  },
  {
    id: 10,
    tags: ['Especial', 'com leite'],
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    img: ChocolateQuente,
    amountInShoppingCart: 0,
  },
  {
    id: 11,
    tags: ['especial', 'alcoólico', 'gelado'],
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    img: CoffeeCubano,
    amountInShoppingCart: 0,
  },
  {
    id: 12,
    tags: ['especial'],
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    img: CoffeeHavaiano,
    amountInShoppingCart: 0,
  },
  {
    id: 13,
    tags: ['especial'],
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    img: CoffeeArabe,
    amountInShoppingCart: 0,
  },
  {
    id: 14,
    tags: ['especial', 'alcoólico'],
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    img: CoffeeIrlands,
    amountInShoppingCart: 0,
  },
]
